### ISSUE TITLE
missing Data file

### ISSUE THREAD

**Issue by qinlincmu** [BDEvan5/f1tenth_benchmarks#2]
Can not run many scripts under \run_scripts

1. drl.racing.py 
raise ValueError(f"Unknown reward function: {params.reward}")
ValueError: Unknown reward function: progress

2. purepursuit_racing.py 
FileNotFoundError: ../Data/racelines/mu60/aut_raceline.csv not found. There is no Data file.

**Comment by bakhbyergyen7** [comment]
1. I believe the first issue has to do with capitalization error: try Progress instead of progress
2. Just try giving global path, and it should work

**Comment by raphajaner** [comment]
We assume the issue is solved @qinlincmu , but you are welcome to open it again if the problem persists :)
